version: '3'
services:
  back-end:
    build: ./locallibrary
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    container_name: banco_postgres_crc
    environment:
      POSTGRES_DB: banco_postgres_crc
      POSTGRES_USER: crc
      POSTGRES_PASSWORD: crc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: